### ISSUE TITLE
Respect GitHub abuse rate limits

### ISSUE THREAD

**Issue by Ajedi32** [artzub/GitHubVisualizer#64]
When loading data from large repos, with a large climit, occasionally this visualizer will hit GitHub's [abuse rate limits](https://developer.github.com/v3/#abuse-rate-limits) and as a result, requests will begin to fail.

In this case, the correct behavior should be to wait the number of seconds in the Retry-After header and try again. See: https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

Unfortunately that isn't currently what happens. Instead the app tries to plough ahead, and as a result fails to load much of the commit data.

**Comment by artzub** [comment]
Yes. You are right!

I didn't apply this way.

But you can try to use your ClientID and SecrtetKey into a special section of settings on the right side.
![image](https://user-images.githubusercontent.com/134249/30743835-83b5e8ae-9fc9-11e7-9330-a50c0a7da0d7.png)
I hope it should prevent the rapid achievement of the limit, because it your unique client id, that's not common.

I'll try to fix it at when I have free time.
